language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

env:
    - WITH_CYTHON=true
    - WITH_CYTHON=false

before_install:
    - pip install git+https://github.com/pytoolz/toolz.git
    - pip install cython

install:
    # *.c files aren't in the repo, so we must always create them
    - python setup.py build_ext --inplace --with-cython
    - if [[ $WITH_CYTHON == 'false' ]]; then
    -     rm cytoolz/*.so
    -     python setup.py build_ext --inplace --without-cython
    - fi

# commands to run tests
script:
    - nosetests --with-doctest cytoolz

notifications:
  email: false
