language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

matrix:
    - CYTHON_VERSION=0.22
    - CYTHON_VERSION=0.17.4
    - CYTHON_VERSION=0.17.1
    - CYTHON_VERSION=0.14.1

before_install:
    - pip install git+https://github.com/pytoolz/toolz.git
    - pip install cython==$CYTHON_VERSION

install:
    - python setup.py build_ext --inplace --with-cython

# commands to run tests
script:
    - nosetests --with-doctest cytoolz

notifications:
  email: false
